name: dencode
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  awesome_snackbar_content: ^0.0.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.1
  google_fonts: ^2.3.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  loading_animation_widget: ^1.1.0+3
  mobile_scanner: ^2.0.0
  path_provider: ^2.0.11
  permission_handler: ^9.2.0
  qr_flutter: ^4.0.0
  salomon_bottom_bar: ^3.3.1
  screenshot: ^1.2.3
  share_plus: ^4.0.8
  top_snackbar_flutter: ^1.1.1
  unicons: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.8
  change_app_package_name: ^1.0.0
  flutter_launcher_icons_maker: "^0.10.1"
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/bg/

# flutter_native_splash:
#   # color: "#42a5f5"
#   background_image: "assets/splash.png"
#   android_12:
# flutter_icons:
#   android: true
#   ios: true
#   macos: true
#   windows: true
#   web: true
#   image_path: "assets/icon.png"
